### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by oleg-nenashev**
It will not be passing until https://github.com/jenkinsci/discard-old-build-plugin/pull/11 is finalized, but I think it worth integrating it anyway.

@nisarg1499 @BenjaminBeggs

### CODE REVIEW

**Comment by BenjaminBeggs** [comment]
Agreed. This will be integrated.

**Comment by oleg-nenashev** [comment]
Failing CI is better than no CI :)

**Comment by BenjaminBeggs** [comment]
I will be modifying some of the build conditions in hopes of having the plugin pass tests without some of the version bumps in PR#11 which impact backwards compatibility with legacy Jenkins instances.

**Comment by nisarg1499** [comment]
@BenjaminBeggs 
In your commit why linux platform is written twice? Any specific reason ? Instead in one platform java version should be added.

**Comment by nisarg1499** [comment]
> @BenjaminBeggs
> In your commit why linux platform is written twice? Any specific reason ? Instead in one platform java version should be added.

Ohh I just saw your second commit. Now it seems better than first one.

**Comment by BenjaminBeggs** [comment]
There will likely be a set of commits here while I work this out. Stay tuned :)

**Comment by oleg-nenashev** [comment]
IMHO it does not wort spending time on getting Jenkinsfile working with 1.515. It will likely work after some tweaks, but there is no sense to support such old version. My proposal would be to just get the original version in place and then push #11 forward. 

I know that @martinda wants to have Jenkins 1.x support, so maybe we could agree on Jenkins 1.642.x and Java 7 as an intermediate target.

**Comment by BenjaminBeggs** [comment]
I will merge all good practice recommendations from PR#11. @martinda can provide his opinion on the Jenkins version to use here. To have tests back in-place for PR's I have merged the Jenkinsfile using 1.642.x, though version number is easy to change if it introduces compatibility problems.

**Comment by oleg-nenashev** [comment]
Note that `jenkins` argument likely makes no effect until the master branch is updated to recent parent POMs

**Comment by oleg-nenashev** [comment]
Specifically, 2.0+ is needed

**Comment by martinda** [comment]
Intermediates up to 1.651.3 should work for me. Thanks.

**Pull request merged**
