### PR TITLE
[Jenkins-12615] Warn users when no builds will be discarded

### PR DESCRIPTION
**Pull request by nisarg1499**
See [Jenkins-12615](https://issues.jenkins-ci.org/browse/JENKINS-12615)

### **Proposed changelog entries**
- Added if condition in the perform method checking value of numToKeep and daysToKeep.

### **Desired reviewers**
@oleg-nenashev  @BenjaminBeggs

### CODE REVIEW

**Comment by BenjaminBeggs** [comment]
Good addition. I will merge this.

**Comment by BenjaminBeggs** [comment]
These changes seemed innocuous enough but now that I work to reinstate proper unit tests for PR's I see that it breaks the current unit tests. You will need to update the unit tests if you'd like to have these changes implemented. Sorry, but I will need to revert it.

**Comment by nisarg1499** [comment]
> These changes seemed innocuous enough but now that I work to reinstate proper unit tests for PR's I see that it breaks the current unit tests. You will need to update the unit tests if you'd like to have these changes implemented. Sorry, but I will need to revert it.

Okay. I will look at current unit tests and will try to update the tests for adding this feature. Can you just provide me some initial guidance regarding the tests and what to look for updating the tests.
@BenjaminBeggs @oleg-nenashev

**Comment by BenjaminBeggs** [comment]
I expect you'll need to look at the error log for unit tests when running your PR, and see why your added code logic is causing them to fail. Just check the logs as a starting point.

**Comment by nisarg1499** [comment]
> I expect you'll need to look at the error log for unit tests when running your PR, and see why your added code logic is causing them to fail. Just check the logs as a starting point.

@BenjaminBeggs 
[There is a method for NoCondition](https://github.com/jenkinsci/discard-old-build-plugin/blob/master/src/test/java/org/jenkinsci/plugins/discardbuild/DiscardBuildPublisherTest.java#L68) in the tests, then wouldn't it take care of this extra lines of code ?
I don't know, I am just asking.

**Comment by BenjaminBeggs** [comment]
I am not sure. The test must be failing because of some logical trouble relative to the unit test conditions. The tests aren’t especially complicated, so you should be able to discern this by some review and testing.

**Pull request merged**
